# Generated by Django 5.2.6 on 2025-09-25 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playbackposition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='video',
        ),
        migrations.DeleteModel(
            name='PlaybackPosition',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
